# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - "6"
before_script:
  - npm install
  - node write-build-info.js
script:
  - npm run-script build -- --prod
after_success:
  - npm run-script deploy -- --token "$FIREBASE_TOKEN"
env:
  global:
  - AUTHOR_EMAIL: "travis@build.local"
